//
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"https://petstore.swagger.io/v2";

/** OAuth 2 Client ID */
/** Replace the value of OAuthClientId with an appropriate value */
NSString* Configuration_OAuthClientId = @"TODO: Replace";

/** OAuth 2 Redirection endpoint or Callback Uri */
/** Replace the value of OAuthRedirectUri with an appropriate value */
NSString* Configuration_OAuthRedirectUri = @"TODO: Replace";

