//
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef SwaggerPetstore_Configuration_h
#define SwaggerPetstore_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

/** OAuth 2 Client ID */
/** extern reference to the config variable OAuthClientId */
extern NSString* Configuration_OAuthClientId;

/** OAuth 2 Redirection endpoint or Callback Uri */
/** extern reference to the config variable OAuthRedirectUri */
extern NSString* Configuration_OAuthRedirectUri;

#endif
