//
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_OAUTHSCOPEENUM
#define APIMATIC_OAUTHSCOPEENUM
 
enum OAuthScopeEnum
{
        OAuthScopeWritepets, //modify pets in your account
        OAuthScopeReadpets, //read your pets
};

#endif