//
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "Pet.h"

@implementation Pet

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize mcategory;

/**
* TODO: Write general description for this method
*/
@synthesize name;

/**
* TODO: Write general description for this method
*/
@synthesize photoUrls;

/**
* TODO: Write general description for this method
*/
@synthesize tags;

/**
* pet status in the store
*/
@synthesize status;

 /**
 * For serialization of enum Status1Enum type property as NSString*
 */
-(id) JSONObjectForStatus
{
     
    return [Status1EnumHelper stringFromStatus1Enum:(enum Status1Enum) status withDefault: nil];

}

/**
 * For deserialization of enum Status1Enum type property from NSString*
 */
 
-(void)setStatusWithNSString:(NSString*) strValue
{
    status = [Status1EnumHelper status1EnumFromString:(NSString*) strValue];
}




/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"category": @"mcategory",
        @"name": @"name",
        @"photoUrls": @"photoUrls",
        @"tags": @"tags",
        @"status": @"status"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end