//
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_STATUS1ENUMHELPER
#define APIMATIC_STATUS1ENUMHELPER

#include "Status1Enum.h"

/**
* Helper class interface for Status1Enum to NSString conversion
*/
@interface Status1EnumHelper : NSObject

+(id) stringFromStatus1Enum:(enum Status1Enum) status1Enum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromStatus1EnumArray:(NSArray<NSNumber*>*) array;


+(enum Status1Enum) status1EnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) status1EnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif