//
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_STATUS2ENUMHELPER
#define APIMATIC_STATUS2ENUMHELPER

#include "Status2Enum.h"

/**
* Helper class interface for Status2Enum to NSString conversion
*/
@interface Status2EnumHelper : NSObject

+(id) stringFromStatus2Enum:(enum Status2Enum) status2Enum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromStatus2EnumArray:(NSArray<NSNumber*>*) array;


+(enum Status2Enum) status2EnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) status2EnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif