//
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_STATUS2ENUM
#define APIMATIC_STATUS2ENUM
 
enum Status2Enum
{
        Status2Available, //TODO: Write general description for this method
        Status2Pending, //TODO: Write general description for this method
        Status2Sold, //TODO: Write general description for this method
};

#endif