//
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_STATUS1ENUM
#define APIMATIC_STATUS1ENUM
 
enum Status1Enum
{
        Status1Available, //TODO: Write general description for this method
        Status1Pending, //TODO: Write general description for this method
        Status1Sold, //TODO: Write general description for this method
};

#endif