//
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "Status1EnumHelper.h"

/**
* Helper class implementation for Status1Enum to NSString conversion
*/
@implementation Status1EnumHelper

+(id) stringFromStatus1Enum:(enum Status1Enum) status1Enum withDefault: (id) defaultValue
{
    switch(status1Enum)
    {
        case Status1Available:
            return @"available";

        case Status1Pending:
            return @"pending";

        case Status1Sold:
            return @"sold";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromStatus1EnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [Status1EnumHelper stringFromStatus1Enum:(enum Status1Enum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum Status1Enum) status1EnumFromString:(NSString*) strValue
{
    NSArray* Status1EnumArray = [NSArray arrayWithObjects:
                                        @"available",
                                        @"pending",
                                        @"sold",
                                        nil];

    return (enum Status1Enum) [Status1EnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) status1EnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ Status1EnumHelper status1EnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end