//
//  SwaggerPetstore
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "NSDate+extension.h"
#import "Order.h"

@interface StoreController : BaseController

/**
* Completion block definition for asynchronous call to getInventory */
typedef void (^CompletedGetInventory)(BOOL success, HttpContext* context, NSDictionary* response, NSError* error);

/**
* Returns a map of status codes to quantities
*/
- (void) getInventoryWithCompletionBlock:(CompletedGetInventory) onCompleted;

/**
* Completion block definition for asynchronous call to placeOrder */
typedef void (^CompletedPostPlaceOrder)(BOOL success, HttpContext* context, Order* response, NSError* error);

/**
* Place an order for a pet
* @param    body    Required parameter: order placed for purchasing the pet
*/
- (void) createPlaceOrderAsyncWithBody:(Order*) body
                completionBlock:(CompletedPostPlaceOrder) onCompleted;

/**
* Completion block definition for asynchronous call to getOrderById */
typedef void (^CompletedGetOrderById)(BOOL success, HttpContext* context, Order* response, NSError* error);

/**
* For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
* @param    orderId    Required parameter: ID of pet that needs to be fetched
*/
- (void) getOrderByIdAsyncWithOrderId:(long) orderId
                completionBlock:(CompletedGetOrderById) onCompleted;

/**
* Completion block definition for asynchronous call to deleteOrder */
typedef void (^CompletedDeleteOrder)(BOOL success, HttpContext* context, NSError* error);

/**
* For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
* @param    orderId    Required parameter: ID of the order that needs to be deleted
*/
- (void) deleteOrderAsyncWithOrderId:(long) orderId
                completionBlock:(CompletedDeleteOrder) onCompleted;

@end